- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Priyanka user exists"
    user:
      name: Priyanka
      state: present
  - name: "ensure Alex user exists"
    user:
      name: alex
      state: present
      
